// This file was automatically generated by informer-gen

package v1alpha1

import (
	versioned "crd-controller/pkg/client/clientset/versioned"
	internalinterfaces "crd-controller/pkg/client/informers/externalversions/internalinterfaces"
	time "time"

	crd_emruz_com_v1alpha1 "crd-controller/pkg/apis/crd.emruz.com/v1alpha1"
	v1alpha1 "crd-controller/pkg/client/listers/crd.emruz.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CustomDeploymentInformer provides access to a shared informer and lister for
// CustomDeployments.
type CustomDeploymentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CustomDeploymentLister
}

type customDeploymentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCustomDeploymentInformer constructs a new informer for CustomDeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCustomDeploymentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCustomDeploymentInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCustomDeploymentInformer constructs a new informer for CustomDeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCustomDeploymentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1alpha1().CustomDeployments(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1alpha1().CustomDeployments(namespace).Watch(options)
			},
		},
		&crd_emruz_com_v1alpha1.CustomDeployment{},
		resyncPeriod,
		indexers,
	)
}

func (f *customDeploymentInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCustomDeploymentInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *customDeploymentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&crd_emruz_com_v1alpha1.CustomDeployment{}, f.defaultInformer)
}

func (f *customDeploymentInformer) Lister() v1alpha1.CustomDeploymentLister {
	return v1alpha1.NewCustomDeploymentLister(f.Informer().GetIndexer())
}
