// This file was automatically generated by lister-gen

package v1alpha1

// CustomDeploymentListerExpansion allows custom methods to be added to
// CustomDeploymentLister.
type CustomDeploymentListerExpansion interface{}

// CustomDeploymentNamespaceListerExpansion allows custom methods to be added to
// CustomDeploymentNamespaceLister.
type CustomDeploymentNamespaceListerExpansion interface{}
